### PR TITLE
feat: add shy-sidebery.css

### PR DESCRIPTION
**Pull request by asyncedd**
This commit adds the CSS module, shy-sideberry.css. This does:
- Style sidebery without needing to import anything to the sidebery style config
- uhhh yeah, just that really lol.

lmk if there's any guidelines for styling

### CODE REVIEW

**Comment by asyncedd** [comment]
ping: @Naezr

**Comment by asyncedd** [comment]
somehow this broke

**Comment by Naezr** [comment]
This PR is too raw to implement. I intend to split the entire `userContent.css` into separate files. Something like `shy-sideberry.css`, `shy-new-tab.css`, etc. Thanks for the example

**Comment by asyncedd** [comment]
> I intend to split the entire `userContent.css` into separate files. Something like `shy-sideberry.css`, `shy-new-tab.css`, etc.

I think I can do that. If you'd want, I could do it - but if not, you could just close this PR I guess :P

**Comment by Naezr** [comment]
I'm already working on it myself, so don't do that

**Pull request closed without merging**
